main:
  - name: "filosofi"
    url: "/filosofi/"
    weight: 1

  - name: "teknologi"
    url: "/teknologi/"
    weight: 2

  - name: "kultur"
    url: "/kultur/"
    weight: 3

  - name: "dagbog"
    url: "/dagbog/"
    weight: 4

  - name: "om siden"
    url: "/om-siden/"
    weight: 5
